### ISSUE TITLE
How to set the initial condition of the advection equation?

### ISSUE THREAD

**Issue by bugsuse** [relmonta/hyphai#1]
It's a very interesting and solid work!

I have a question about how you set the initial condition of the advection equation in the HYPHAI and HYPHAI-2 architecture.  Using a learnable function as the initial condition or just using the observation as the initial condition? or anything else?

Thanks!

**Comment by relmonta** [comment]
Thank you for your interest and kind words!
The initial condition is simply set as the one-hot encoded observation at $t=0$. 
An example is given [here](https://github.com/relmonta/hyphai/blob/main/examples/hyphai-1_forecast_example.ipynb).
If you have any further questions or need clarification, feel free to ask!

**Comment by bugsuse** [comment]
> Thank you for your interest and kind words! The initial condition is simply set as the one-hot encoded observation at t=0. An example is given [here](https://github.com/relmonta/hyphai/blob/main/examples/hyphai-1_forecast_example.ipynb). If you have any further questions or need clarification, feel free to ask!

Thanks for your reply!
